### ISSUE TITLE
Warning: component lists rendered with v-for should have explicit keys

### ISSUE THREAD

**Issue by crimaniak** [rosendin/vue-bulma-pagination#2]
It needs additional 'key' attribute at [Pagination.Vue line 7](https://github.com/roseware/vue-bulma-pagination/blob/master/src/Pagination.vue#L7).
Like <component v-for="element in elements" :key="element.page" ...>

Full message text from Webpack:

```
./~/vue-loader/lib/template-compiler?{"id":"data-v-62cc492c","transformToRequire":{"audio":"src"}}!./~/vue-loader/lib/selector.js?type=template&index=0!./~/vue-2-bulma-pagination/src/Pagination.vue
(Emitted value instead of an instance of Error) <component v-for="element in elements">: component lists rendered with v-for should have explicit keys. See https://vuejs.org/guide/list.html#key for more info.
 @ ./~/vue-2-bulma-pagination/src/Pagination.vue 9:2-200
 @ ./~/vue-2-bulma-pagination/index.js
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/BasicTable.vue
 @ ./src/components/BasicTable.vue
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/home/device-selector.vue
 @ ./src/components/home/device-selector.vue
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/home/page.vue
 @ ./src/components/home/page.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

```

**Comment by Romick2005** [comment]
+

**Comment by rosendin** [comment]
Fixed in https://github.com/rosendin/vue-bulma-pagination/pull/7, just download the new version 0.0.8.

**Comment by balduinofernando** [comment]
Dude this problem is still there, could you update the code?
If we go to the "node_modules/vue-bulma-pagination/src/Pagination.vue" and change it from there it works, but should be good if you realease a bugfix.
